#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# copyright: 2011 to the present, california institute of technology.
# all rights reserved. united states government sponsorship acknowledged.
# any commercial use must be negotiated with the office of technology transfer
# at the california institute of technology.
# 
# this software may be subject to u.s. export control laws. by accepting this
# software, the user agrees to comply with all applicable u.s. export laws and
# regulations. user has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# installation and use of this software is restricted by a license agreement
# between the licensee and the california institute of technology. it is the
# user's responsibility to abide by the terms of the license agreement.
#
# Author: Eric Gurrola
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





import os

Import('env')
Import('envapplications')
Import('envcomponents')
envcontrib = env.Clone()
package = 'contrib'
envcontrib['PACKAGE'] = os.path.join(envcomponents['PACKAGE'],package)
envcontrib['INSTALL_COMPS'] = os.path.join(envcomponents['INSTALL_PATH'],package)
envcontrib['INSTALL_APPS'] = envapplications['INSTALL_PATH']
envcontrib['INSTALL_PATH'] = envcontrib['INSTALL_COMPS']
install = envcontrib['INSTALL_PATH']

initFile = '__init__.py'
if not os.path.exists(initFile):
	fout = open(initFile,"w")
	fout.write("#!/usr/bin/env python")
	fout.close()

listFiles = [initFile]
envcontrib.Install(install,listFiles)
envcontrib.Alias('install',install)
Export('envcontrib')

issi = os.path.join('issi','SConscript')
SConscript(issi)
snaphu = os.path.join('Snaphu','SConscript')
SConscript(snaphu)
demUtils = os.path.join('demUtils','SConscript')
SConscript(demUtils)
frameUtils = os.path.join('frameUtils','SConscript')
SConscript(frameUtils)
unwUtils = os.path.join('UnwrapComp','SConscript')
SConscript(unwUtils)

if 'MOTIFLIBPATH' in envcontrib.Dictionary():
    mdx = os.path.join('mdx','SConscript')
    SConscript(mdx)

rfi = os.path.join('rfi', 'SConscript')
SConscript(rfi)
