#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# copyright: 2013 to the present, california institute of technology.
# all rights reserved. united states government sponsorship acknowledged.
# any commercial use must be negotiated with the office of technology transfer
# at the california institute of technology.
# 
# this software may be subject to u.s. export control laws. by accepting this
# software, the user agrees to comply with all applicable u.s. export laws and
# regulations. user has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# installation and use of this software is restricted by a license agreement
# between the licensee and the california institute of technology. it is the
# user's responsibility to abide by the terms of the license agreement.
#
# Author: Piyush Agram
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




import os

Import('envdemUtils')
envcorrectGeoid = envdemUtils.Clone()
package = envcorrectGeoid['PACKAGE']
project = 'correct_geoid_i2_srtm'
envcorrectGeoid['PROJECT'] = project
install = envcorrectGeoid['PRJ_SCONS_INSTALL'] +'/' + package 
helpList,installHelp = envcorrectGeoid['HELP_BUILDER'](envcorrectGeoid,'../__init__.py',install)
envcorrectGeoid.Install(installHelp,helpList)
envcorrectGeoid.Alias('install',installHelp)

listFiles = ['Correct_geoid_i2_srtm.py', 'egm96geoid.dat']
envcorrectGeoid.Install(install,listFiles)
envcorrectGeoid.Alias('install',install)
Export('envcorrectGeoid')
bindingsScons="bindings/SConscript"
SConscript(bindingsScons, variant_dir = envcorrectGeoid['PRJ_SCONS_BUILD'] + '/' + package + '/' + project + '/bindings')
includeScons = 'include/SConscript'
SConscript(includeScons)
srcScons = 'src/SConscript'
SConscript(srcScons,variant_dir=envcorrectGeoid['PRJ_SCONS_BUILD'] + '/' + package + '/' + project + '/src')
