#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# copyright: 2011 to the present, california institute of technology.
# all rights reserved. united states government sponsorship acknowledged.
# any commercial use must be negotiated with the office of technology transfer
# at the california institute of technology.
# 
# this software may be subject to u.s. export control laws. by accepting this
# software, the user agrees to comply with all applicable u.s. export laws and
# regulations. user has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# installation and use of this software is restricted by a license agreement
# between the licensee and the california institute of technology. it is the
# user's responsibility to abide by the terms of the license agreement.
#
# Author: Eric Gurrola
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




import os

Import('envmdx')
envmdx.Append( CCFLAGS=['-DSUN','-DIO64','-I'+envmdx['MOTIFINCPATH'],'-I'+envmdx['X11INCPATH']] )
envmdx.PrependUnique( LIBPATH=[envmdx['MOTIFLIBPATH'],envmdx['X11LIBPATH']] )
envmdx.Append( FORTRANFLAGS=['-DSUN','-DIO64','-DGFORTRAN'] )

listFiles = ['graphx_mdx.c','rdf_reader_subs.f','mdx_subs.F']
build = envmdx['PRJ_LIB_DIR']
lib = envmdx.Library(target='mdx',source=listFiles)
envmdx.Install(build,lib)
envmdx.Alias('build',build)

libList = ['mdx','Xm','Xt','X11']
envmdx.PrependUnique( LIBS=libList )

#Remove unnecessary libraries 'gdal', 'hdf5', 'fftw3f' from envmdx['LIBS']
#loop through all incidences of these libraries since they seem to accumulate
for i in range(envmdx['LIBS'].count('gdal')): envmdx['LIBS'].remove('gdal')
for i in range(envmdx['LIBS'].count('hdf5')): envmdx['LIBS'].remove('hdf5')
for i in range(envmdx['LIBS'].count('fftw3f')): envmdx['LIBS'].remove('fftw3f')

install = os.path.join(envmdx['PRJ_SCONS_INSTALL'],'bin')
program = envmdx.Program(target='mdx', source='mdx_main.F')
envmdx.Install(install,program)
envmdx.Alias('install',install)
