#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# copyright: 2010 to the present, california institute of technology.
# all rights reserved. united states government sponsorship acknowledged.
# any commercial use must be negotiated with the office of technology transfer
# at the california institute of technology.
# 
# this software may be subject to u.s. export control laws. by accepting this
# software, the user agrees to comply with all applicable u.s. export laws and
# regulations. user has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# installation and use of this software is restricted by a license agreement
# between the licensee and the california institute of technology. it is the
# user's responsibility to abide by the terms of the license agreement.
#
# Author: Giangi Sacco
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





import os

Import('envcpxmag2rg')
package = envcpxmag2rg['PACKAGE']
install = envcpxmag2rg['PRJ_SCONS_INSTALL'] + '/' + package 
build = envcpxmag2rg['PRJ_SCONS_BUILD'] + '/' + package 
libList = ['cpxmag2rg','DataAccessor','InterleavedAccessor']
envcpxmag2rg.PrependUnique(LIBS = libList)
module = envcpxmag2rg.LoadableModule(target = 'cpxmag2rg.abi3.so', source = 'cpxmag2rgmodule.cpp') 
envcpxmag2rg.Install(install,module)
envcpxmag2rg.Alias('install',install)
envcpxmag2rg.Install(build,module)
envcpxmag2rg.Alias('build',build)
