#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# copyright: 2010 to the present, california institute of technology.
# all rights reserved. united states government sponsorship acknowledged.
# any commercial use must be negotiated with the office of technology transfer
# at the california institute of technology.
# 
# this software may be subject to u.s. export control laws. by accepting this
# software, the user agrees to comply with all applicable u.s. export laws and
# regulations. user has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# installation and use of this software is restricted by a license agreement
# between the licensee and the california institute of technology. it is the
# user's responsibility to abide by the terms of the license agreement.
#
# Author: Walter Szeliga
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




import os

Import('envmroipac')
envcorrelation = envmroipac.Clone()
package = envcorrelation['PACKAGE']
project = 'correlation'
envcorrelation['PROJECT'] = project
Export('envcorrelation')


bindingsScons = 'bindings/SConscript'
SConscript(bindingsScons,variant_dir = envcorrelation['PRJ_SCONS_BUILD'] + '/' + package + '/'  + project + '/bindings')

includeScons = 'include/SConscript'
SConscript(includeScons)


srcScons = os.path.join('src','SConscript')
SConscript(srcScons,variant_dir = envcorrelation['PRJ_SCONS_BUILD'] + '/' + package + '/'  + project + '/src')

install = os.path.join(envcorrelation['PRJ_SCONS_INSTALL'],package,project)
envcorrelation.Install(install,['__init__.py','correlation.py'])
envcorrelation.Alias('install',install)

