#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# copyright: 2012 to the present, california institute of technology.
# all rights reserved. united states government sponsorship acknowledged.
# any commercial use must be negotiated with the office of technology transfer
# at the california institute of technology.
# 
# this software may be subject to u.s. export control laws. by accepting this
# software, the user agrees to comply with all applicable u.s. export laws and
# regulations. user has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# installation and use of this software is restricted by a license agreement
# between the licensee and the california institute of technology. it is the
# user's responsibility to abide by the terms of the license agreement.
#
# Author: Giangi Sacco
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





import os

Import('envstdproc1')
envcorrect = envstdproc1.Clone()
package = envcorrect['PACKAGE']
project = 'correct'
install = envcorrect['PRJ_SCONS_INSTALL'] + '/' + package + '/' + project
initFile = '__init__.py'
if not os.path.exists(initFile):
	fout = open(initFile,"w")
	fout.write("#!/usr/bin/env python")
	fout.close()

listFiles = ['Correct.py',initFile]
helpList,installHelp = envcorrect['HELP_BUILDER'](envcorrect,'__init__.py',install)
envcorrect.Install(installHelp,helpList)
envcorrect.Alias('install',installHelp)
envcorrect.Install(install,listFiles)
envcorrect.Alias('install',install)
envcorrect['PROJECT'] = project
Export('envcorrect')
bindingsScons = 'bindings/SConscript'
SConscript(bindingsScons,variant_dir = envcorrect['PRJ_SCONS_BUILD'] + '/' + package + '/'  + project + '/bindings')
includeScons = 'include/SConscript'
SConscript(includeScons)
srcScons = 'src/SConscript'
SConscript(srcScons,variant_dir = envcorrect['PRJ_SCONS_BUILD'] + '/' + package + '/'  + project + '/src')
