#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# copyright: 2010 to the present, california institute of technology.
# all rights reserved. united states government sponsorship acknowledged.
# any commercial use must be negotiated with the office of technology transfer
# at the california institute of technology.
# 
# this software may be subject to u.s. export control laws. by accepting this
# software, the user agrees to comply with all applicable u.s. export laws and
# regulations. user has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# installation and use of this software is restricted by a license agreement
# between the licensee and the california institute of technology. it is the
# user's responsibility to abide by the terms of the license agreement.
#
# Author: Giangi Sacco
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





import os

Import('envcomponents')
package = os.path.join('components','stdproc')
envstdproc = envcomponents.Clone()
envstdproc['PACKAGE'] = package

install = os.path.join(envcomponents['PRJ_SCONS_INSTALL'],package)

initFile = '__init__.py'
if not os.path.exists(initFile):
	fout = open(initFile,"w")
	fout.write("#!/usr/bin/env python")
	fout.close()

listFiles = [initFile]
envstdproc.Install(install,listFiles)
envstdproc.Alias('install',install)
Export('envstdproc')
alosreformat = os.path.join('alosreformat','SConscript')
SConscript(alosreformat)
orbit = os.path.join('orbit','SConscript')
SConscript(orbit)
stdproc = os.path.join('stdproc','SConscript')
SConscript(stdproc)
rectify = os.path.join('rectify','SConscript')
SConscript(rectify)
model = os.path.join('model','SConscript')
SConscript(model)
