#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# copyright: 2010 to the present, california institute of technology.
# all rights reserved. united states government sponsorship acknowledged.
# any commercial use must be negotiated with the office of technology transfer
# at the california institute of technology.
# 
# this software may be subject to u.s. export control laws. by accepting this
# software, the user agrees to comply with all applicable u.s. export laws and
# regulations. user has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# installation and use of this software is restricted by a license agreement
# between the licensee and the california institute of technology. it is the
# user's responsibility to abide by the terms of the license agreement.
#
# Author: Kosal Khun
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



# Comment: Adapted from Scene/SConscript

import os

Import('envisceobj')
envStack = envisceobj.Clone()
project = 'Stack'
package = envStack['PACKAGE']
Export('envStack')

#srcScons = os.path.join('src','SConscript')
#varDir = os.path.join(envStack['PRJ_SCONS_BUILD'],package,project,'src')
#SConscript(srcScons, variant_dir = varDir)

install = os.path.join(envStack['PRJ_SCONS_INSTALL'],package,project)
listFiles = ['Stack.py','__init__.py']
envStack.Install(install,listFiles)
envStack.Alias('install',install)

