#!/usr/bin/env python3

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# copyright: 2015 to the present, california institute of technology.
# all rights reserved. united states government sponsorship acknowledged.
# any commercial use must be negotiated with the office of technology transfer
# at the california institute of technology.
# 
# this software may be subject to u.s. export control laws. by accepting this
# software, the user agrees to comply with all applicable u.s. export laws and
# regulations. user has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# installation and use of this software is restricted by a license agreement
# between the licensee and the california institute of technology. it is the
# user's responsibility to abide by the terms of the license agreement.
#
# Author: Giangi Sacco
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




#!/usr/bin/env python3
import os

Import('enviscesys')
envDataManager = enviscesys.Clone()
project = 'DataManager'
envDataManager['PROJECT'] = project
package = envDataManager['PACKAGE']
Export('envDataManager')
install = os.path.join(envDataManager['PRJ_SCONS_INSTALL'],package,project)

initFile = '__init__.py'
listFiles = ['TileManager.py','Dem1Manager.py','Dem3Manager.py',
			'SWBDManager.py','SRTMManager.py',initFile]
envDataManager.Install(install,listFiles)
envDataManager.Alias('install',install)
helpList,installHelp = envDataManager['HELP_BUILDER'](envDataManager,'__init__.py',install)
envDataManager.Install(installHelp,helpList)
envDataManager.Alias('install',installHelp)