#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# copyright: 2010 to the present, california institute of technology.
# all rights reserved. united states government sponsorship acknowledged.
# any commercial use must be negotiated with the office of technology transfer
# at the california institute of technology.
# 
# this software may be subject to u.s. export control laws. by accepting this
# software, the user agrees to comply with all applicable u.s. export laws and
# regulations. user has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# installation and use of this software is restricted by a license agreement
# between the licensee and the california institute of technology. it is the
# user's responsibility to abide by the terms of the license agreement.
#
# Author: Giangi Sacco
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



import os
Import('envDataAccessor')
package = envDataAccessor['PACKAGE']
project = envDataAccessor['PROJECT']
install = envDataAccessor['PRJ_SCONS_INSTALL'] + '/' + package
build = envDataAccessor['PRJ_SCONS_BUILD'] + '/' + package + '/' + project
envDataAccessor.AppendUnique(LIBPATH = envDataAccessor['PRJ_LIB_DIR'])
libPath = [envDataAccessor['LIBPATH']]
linkLibs = ['Factories','InterleavedAccessor','DataAccessor','combinedLib']
linkLibs.extend([envDataAccessor['LIBS']])#which fortran and g++ libraries
lib = envDataAccessor.LoadableModule(target = 'DataAccessor.abi3.so', source = 'DataAccessormodule.cpp', LIBS = linkLibs, LIBPATH = libPath)
envDataAccessor.Install(install,lib)
envDataAccessor.Alias('install',install)
envDataAccessor.Install(build,lib)
envDataAccessor.Alias('build',build)

