#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# copyright: 2010 to the present, california institute of technology.
# all rights reserved. united states government sponsorship acknowledged.
# any commercial use must be negotiated with the office of technology transfer
# at the california institute of technology.
# 
# this software may be subject to u.s. export control laws. by accepting this
# software, the user agrees to comply with all applicable u.s. export laws and
# regulations. user has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# installation and use of this software is restricted by a license agreement
# between the licensee and the california institute of technology. it is the
# user's responsibility to abide by the terms of the license agreement.
#
# Author: Giangi Sacco
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




import os

Import('envmroipac')
envgetPegInfo = envmroipac.Clone()
package = envgetPegInfo['PACKAGE']
project = 'getPegInfo'
envgetPegInfo['PROJECT'] = project
Export('envgetPegInfo')

bindingsScons = os.path.join('bindings','SConscript')
bindingsVarDir = os.path.join(envgetPegInfo['PRJ_SCONS_BUILD'],package,project,'bindings')
SConscript(bindingsScons,variant_dir = bindingsVarDir)

includeScons = os.path.join('include','SConscript')
SConscript(includeScons)

srcScons = os.path.join('src','SConscript')
srcVarDir = os.path.join(envgetPegInfo['PRJ_SCONS_BUILD'],package,project,'src')
SConscript(srcScons,variant_dir = srcVarDir)


install = os.path.join(envgetPegInfo['PRJ_SCONS_INSTALL'],package,project)
initFile = '__init__.py'
listFiles = ['Get_peg_info.py',initFile]
envgetPegInfo.Install(install,listFiles)
envgetPegInfo.Alias('install',install)
