#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# copyright: 2009 to the present, california institute of technology.
# all rights reserved. united states government sponsorship acknowledged.
# any commercial use must be negotiated with the office of technology transfer
# at the california institute of technology.
# 
# this software may be subject to u.s. export control laws. by accepting this
# software, the user agrees to comply with all applicable u.s. export laws and
# regulations. user has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# installation and use of this software is restricted by a license agreement
# between the licensee and the california institute of technology. it is the
# user's responsibility to abide by the terms of the license agreement.
#
# Authors: Giangi Sacco, Eric Gurrola
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




#!/usr/bin/env python

import os

Import('env')
package = 'defaults'
envdefaults = env.Clone()
envdefaults['PACKAGE'] = package
install = os.path.join(envdefaults['PRJ_SCONS_INSTALL'], package)

listFiles = ['__init__.py']
envdefaults.Install(install,listFiles)
envdefaults.Alias('install',install)

if not 'DEFAULTS_SCONS_INSTALL' in envdefaults:
    envdefaults['DEFAULTS_SCONS_INSTALL']  = envdefaults['PRJ_SCONS_INSTALL']

Export('envdefaults')

logging = os.path.join('logging', 'SConscript')
SConscript(logging)
plugins= os.path.join('plugins', 'SConscript')
SConscript(plugins)
