#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# copyright: 2010 to the present, california institute of technology.
# all rights reserved. united states government sponsorship acknowledged.
# any commercial use must be negotiated with the office of technology transfer
# at the california institute of technology.
# 
# this software may be subject to u.s. export control laws. by accepting this
# software, the user agrees to comply with all applicable u.s. export laws and
# regulations. user has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# installation and use of this software is restricted by a license agreement
# between the licensee and the california institute of technology. it is the
# user's responsibility to abide by the terms of the license agreement.
#
# Author: Giangi Sacco
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




import os

Import('envALOS_fbd2fbs')
package = envALOS_fbd2fbs['PACKAGE']
project = envALOS_fbd2fbs['PROJECT']
build = os.path.join(envALOS_fbd2fbs['PRJ_SCONS_BUILD'], package, project,
    'include')
envALOS_fbd2fbs.AppendUnique(CPPPATH = [build])
listFiles = ['ALOS_fbd2fbsmodule.h','ALOS_fbd2fbsmoduleFortTrans.h']
envALOS_fbd2fbs.Install(build,listFiles)
envALOS_fbd2fbs.Alias('build',build)
