#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# copyright: 2010 to the present, california institute of technology.
# all rights reserved. united states government sponsorship acknowledged.
# any commercial use must be negotiated with the office of technology transfer
# at the california institute of technology.
# 
# this software may be subject to u.s. export control laws. by accepting this
# software, the user agrees to comply with all applicable u.s. export laws and
# regulations. user has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# installation and use of this software is restricted by a license agreement
# between the licensee and the california institute of technology. it is the
# user's responsibility to abide by the terms of the license agreement.
#
# Author: Giangi Sacco
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





import os

Import('envorbitlib')
build = envorbitlib['PRJ_LIB_DIR'] 
listFiles = ['ave_tpsch.f90','unitvec.f90','dot.f90','get_tpsch.f90','latlon.F', 'geo_hdg.F', 'radar_to_xyz.F', 'convert_sch_to_xyz.F', 'convert_schdot_to_xyzdot.F', 'lincomb.F', 'matvec.F', 'schbasis.F', 'matmat.F', 'tranmat.F', 'curvature.F']
lib = envorbitlib.Library(target = 'orbitLib', source = listFiles)
envorbitlib.Install(build,lib)
envorbitlib.Alias('build',build)
