#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# copyright: 2010 to the present, california institute of technology.
# all rights reserved. united states government sponsorship acknowledged.
# any commercial use must be negotiated with the office of technology transfer
# at the california institute of technology.
# 
# this software may be subject to u.s. export control laws. by accepting this
# software, the user agrees to comply with all applicable u.s. export laws and
# regulations. user has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# installation and use of this software is restricted by a license agreement
# between the licensee and the california institute of technology. it is the
# user's responsibility to abide by the terms of the license agreement.
#
# Author: Giangi Sacco
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





import os

Import('envgeo2rdr')
package = envgeo2rdr['PACKAGE']
project = envgeo2rdr['PROJECT']
install = envgeo2rdr['PRJ_SCONS_INSTALL'] + '/' + package + '/' + project
build = envgeo2rdr['PRJ_SCONS_BUILD'] + '/' + package + '/' + project
libList = ['gomp','geo2rdr','orbitLib','combinedLib','DataAccessor','InterleavedAccessor','utilLib','StdOEL']
envgeo2rdr.PrependUnique(LIBS = libList)
module = envgeo2rdr.LoadableModule(target = 'geo2rdr.abi3.so', source = 'geo2rdrmodule.cpp') 
envgeo2rdr.Install(install,module)
envgeo2rdr.Alias('install',install)
envgeo2rdr.Install(build,module)
envgeo2rdr.Alias('build',build)
