#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# copyright: 2010 to the present, california institute of technology.
# all rights reserved. united states government sponsorship acknowledged.
# any commercial use must be negotiated with the office of technology transfer
# at the california institute of technology.
# 
# this software may be subject to u.s. export control laws. by accepting this
# software, the user agrees to comply with all applicable u.s. export laws and
# regulations. user has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# installation and use of this software is restricted by a license agreement
# between the licensee and the california institute of technology. it is the
# user's responsibility to abide by the terms of the license agreement.
#
# Author: Giangi Sacco
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





import os

Import('envstdproc')
package = 'stdproc'
envstdproc1 = envstdproc.Clone()
envstdproc1['PACKAGE'] = envstdproc['PACKAGE'] + '/' + package
install = envstdproc1['PRJ_SCONS_INSTALL'] + '/' + envstdproc1['PACKAGE']
initFile = '__init__.py'
if not os.path.exists(initFile):
	fout = open(initFile,"w")
	fout.write("#!/usr/bin/env python")
	fout.close()
helpList,installHelp = envstdproc1['HELP_BUILDER'](envstdproc1,'__init__.py',install)
envstdproc1.Install(installHelp,helpList)
envstdproc1.Alias('install',installHelp)
listFiles = [initFile]
envstdproc1.Install(install,listFiles)
envstdproc1.Alias('install',install)
Export('envstdproc1')
formslc = 'formslc/SConscript'
SConscript(formslc)
formslcLib = 'formslcLib/SConscript'
SConscript(formslcLib)
#resampTest = 'resampTest/SConscript'
#SConscript(resampTest)
resamp = 'resamp/SConscript'
SConscript(resamp)
resampLib = 'resampLib/SConscript'
SConscript(resampLib)
resamp_image = 'resamp_image/SConscript'
SConscript(resamp_image)
resamp_amps = 'resamp_amps/SConscript'
SConscript(resamp_amps)
resamp_only = 'resamp_only/SConscript'
SConscript(resamp_only)
resamp_slc = 'resamp_slc/SConscript'
SConscript(resamp_slc)
topo = 'topo/SConscript'
SConscript(topo)
correct = 'correct/SConscript'
SConscript(correct)
mocompTSX = 'mocompTSX/SConscript'
SConscript(mocompTSX)
crossmul = 'crossmul/SConscript'
SConscript(crossmul)
estamb = 'estamb/SConscript'
SConscript(estamb)
offsetpoly= 'offsetpoly/SConscript'
SConscript(offsetpoly)
