#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# copyright: 2010 to the present, california institute of technology.
# all rights reserved. united states government sponsorship acknowledged.
# any commercial use must be negotiated with the office of technology transfer
# at the california institute of technology.
# 
# this software may be subject to u.s. export control laws. by accepting this
# software, the user agrees to comply with all applicable u.s. export laws and
# regulations. user has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# installation and use of this software is restricted by a license agreement
# between the licensee and the california institute of technology. it is the
# user's responsibility to abide by the terms of the license agreement.
#
# Author: Giangi Sacco
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





import os
Import('envdemUtils')
envswbdStitcher = envdemUtils.Clone()
package = envswbdStitcher['PACKAGE']
project = 'swbdstitcher'
envswbdStitcher['PROJECT'] = project
Export('envswbdStitcher')


install = os.path.join(envswbdStitcher['PRJ_SCONS_INSTALL'],package)
helpList,installHelp = envswbdStitcher['HELP_BUILDER'](envswbdStitcher,'../__init__.py',install)
envswbdStitcher.Install(installHelp,helpList)
envswbdStitcher.Alias('install',installHelp)

listFiles = ['SWBDStitcher.py']
envswbdStitcher.Install(install,listFiles)
envswbdStitcher.Alias('install',install)
