#! /usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# copyright: 2012 to the present, california institute of technology.
# all rights reserved. united states government sponsorship acknowledged.
# any commercial use must be negotiated with the office of technology transfer
# at the california institute of technology.
# 
# this software may be subject to u.s. export control laws. by accepting this
# software, the user agrees to comply with all applicable u.s. export laws and
# regulations. user has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# installation and use of this software is restricted by a license agreement
# between the licensee and the california institute of technology. it is the
# user's responsibility to abide by the terms of the license agreement.
#
# Author: Eric Gurrola
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





#!/usr/bin/env python
import os

Import('envisceobj')
envInsarProc = envisceobj.Clone()
package = envisceobj['PACKAGE']
project = 'InsarProc'
Export('envInsarProc')

install = os.path.join(envInsarProc['PRJ_SCONS_INSTALL'],package,project)

listFiles = ['__init__.py', 'Factories.py', 'InsarProc.py', '__InsarProc.py','runCoherence.py',
    'runEstimateHeights.py', 'runEstimateHeights_peg.py', 'runFdMocomp.py', 'runFilter.py',
    'runFormSLCTSX.py', 'runFormSLC.py', 'runFormSLCisce.py', 'runGeocode.py',
    'runGrass.py', 'runMocompbaseline.py', 'runOffoutliers.py',
    'runOrbit2sch.py', 'runPrepareResamps.py', 'runPreprocessor.py',
    'runPulseTiming.py', 'runResamp_image.py', 'runResamp_only.py',
    'runResamp.py', 'runOffsetprf.py', 'runOffsetprf_none.py',
    'runOffsetprf_ampcor.py','runOffsetprf_nstage.py', 'runRgoffset.py',
    'runSetmocomppath.py', 'runSetmocomppathFromFrame.py', 'runShadecpx2rg.py',
    'runTopo.py', 'runCorrect.py', 'runUpdatePreprocInfo.py', 'extractInfo.py',
    'createDem.py','runUnwrapGrass.py','runUnwrapSnaphu.py', 'runUnwrapIcu.py',
    'runRgoffset_ampcor.py','runRgoffset_nstage.py', 'runRgoffset_none.py','runCreateWbdMask.py',
    'runMaskImages.py', 'runUnwrap2Stage.py',
]


envInsarProc.Install(install,listFiles)
envInsarProc.Alias('install',install)
helpList,installHelp = envInsarProc['HELP_BUILDER'](envInsarProc,'__init__.py',install)
envInsarProc.Install(installHelp,helpList)
envInsarProc.Alias('install',installHelp)