#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# copyright: 2010 to the present, california institute of technology.
# all rights reserved. united states government sponsorship acknowledged.
# any commercial use must be negotiated with the office of technology transfer
# at the california institute of technology.
# 
# this software may be subject to u.s. export control laws. by accepting this
# software, the user agrees to comply with all applicable u.s. export laws and
# regulations. user has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# installation and use of this software is restricted by a license agreement
# between the licensee and the california institute of technology. it is the
# user's responsibility to abide by the terms of the license agreement.
#
# Author: Giangi Sacco
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




import os

Import('envALOS_fbs2fbd')
package = envALOS_fbs2fbd['PACKAGE']
project = envALOS_fbs2fbd['PROJECT']
install = os.path.join(envALOS_fbs2fbd['PRJ_SCONS_INSTALL'], package, project)
build = os.path.join(envALOS_fbs2fbd['PRJ_SCONS_BUILD'], package, project)
libList = ['utilLib', 'ALOSStd', 'fftw3f']
envALOS_fbs2fbd.PrependUnique(LIBS = libList)
module = envALOS_fbs2fbd.LoadableModule(target = 'ALOS_fbs2fbd.abi3.so',
    source = 'ALOS_fbs2fbdmodule.c')
envALOS_fbs2fbd.Install(install,module)
envALOS_fbs2fbd.Alias('install',install)
envALOS_fbs2fbd.Install(build,module)
envALOS_fbs2fbd.Alias('build',build)
