#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# copyright: 2010 to the present, california institute of technology.
# all rights reserved. united states government sponsorship acknowledged.
# any commercial use must be negotiated with the office of technology transfer
# at the california institute of technology.
# 
# this software may be subject to u.s. export control laws. by accepting this
# software, the user agrees to comply with all applicable u.s. export laws and
# regulations. user has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# installation and use of this software is restricted by a license agreement
# between the licensee and the california institute of technology. it is the
# user's responsibility to abide by the terms of the license agreement.
#
# Author: Walter Szeliga
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



#!/usr/bin/env python

import os

import fnmatch
Import('envSensor')
envSensordb = envSensor.Clone()
package = 'db'
envSensordb['SENSORDB_SCONS_INSTALL'] = os.path.join(
    envSensor['SENSOR_SCONS_INSTALL'], package)

install = envSensordb['SENSORDB_SCONS_INSTALL']

listFiles = ['__init__.py']
envSensordb.Install(install,listFiles)
envSensordb.Alias('install',install)
Export('envSensordb')

SConscript(os.path.join('alos', 'SConscript'))
SConscript(os.path.join('ers', 'SConscript'))
SConscript(os.path.join('jers', 'SConscript'))
SConscript(os.path.join('radarsat', 'SConscript'))
SConscript(os.path.join('risat', 'SConscript'))
SConscript(os.path.join('radarsat_slc', 'SConscript'))
SConscript(os.path.join('risat_slc', 'SConscript'))
SConscript(os.path.join('alos2_slc', 'SConscript'))
SConscript(os.path.join('ers_slc', 'SConscript'))
SConscript(os.path.join('alos_slc', 'SConscript'))
