#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# copyright: 2010 to the present, california institute of technology.
# all rights reserved. united states government sponsorship acknowledged.
# any commercial use must be negotiated with the office of technology transfer
# at the california institute of technology.
# 
# this software may be subject to u.s. export control laws. by accepting this
# software, the user agrees to comply with all applicable u.s. export laws and
# regulations. user has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# installation and use of this software is restricted by a license agreement
# between the licensee and the california institute of technology. it is the
# user's responsibility to abide by the terms of the license agreement.
#
# Author: Giangi Sacco
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





import os

Import('envzenith2los')
package = envzenith2los['PACKAGE']
project = envzenith2los['PROJECT']
install = envzenith2los['PRJ_SCONS_INSTALL'] + '/' + package + '/' + project
build = envzenith2los['PRJ_SCONS_BUILD'] + '/' + package + '/' + project
libList = ['gomp','zenith2los','DataAccessor','InterleavedAccessor']
envzenith2los.PrependUnique(LIBS = libList)
module = envzenith2los.LoadableModule(target = 'zenith2los.abi3.so', source = 'zenith2losmodule.cpp') 
envzenith2los.Install(install,module)
envzenith2los.Alias('install',install)
envzenith2los.Install(build,module)
envzenith2los.Alias('build',build)
