#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# copyright: 2010 to the present, california institute of technology.
# all rights reserved. united states government sponsorship acknowledged.
# any commercial use must be negotiated with the office of technology transfer
# at the california institute of technology.
# 
# this software may be subject to u.s. export control laws. by accepting this
# software, the user agrees to comply with all applicable u.s. export laws and
# regulations. user has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# installation and use of this software is restricted by a license agreement
# between the licensee and the california institute of technology. it is the
# user's responsibility to abide by the terms of the license agreement.
#
# Author: Giangi Sacco
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





import os

Import('envorbit')
envorbitlib = envorbit.Clone()
package = envorbitlib['PACKAGE']
project = 'orbitLib'
envorbitlib['PROJECT'] = project
install = envorbitlib['PRJ_SCONS_INSTALL'] + '/' + package + '/' + project
Export('envorbitlib')
initFile = '__init__.py'
if not os.path.exists(initFile):
	fout = open(initFile,"w")
	fout.write("#!/usr/bin/env python")
	fout.close()
listFiles = ['CalcSchHeightVel.py',initFile]
envorbitlib.Install(install,listFiles)
envorbitlib.Alias('install',install)
srcScons = 'src/SConscript'
SConscript(srcScons,variant_dir = envorbitlib['PRJ_SCONS_BUILD'] + '/' + package + '/' + project + '/src')
