#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# copyright: 2011 to the present, california institute of technology.
# all rights reserved. united states government sponsorship acknowledged.
# any commercial use must be negotiated with the office of technology transfer
# at the california institute of technology.
# 
# this software may be subject to u.s. export control laws. by accepting this
# software, the user agrees to comply with all applicable u.s. export laws and
# regulations. user has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# installation and use of this software is restricted by a license agreement
# between the licensee and the california institute of technology. it is the
# user's responsibility to abide by the terms of the license agreement.
#
# Author: Giangi Sacco
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





import os

Import('envdismphfile')
package = envdismphfile['PACKAGE']
project = envdismphfile['PROJECT']
install = envdismphfile['PRJ_SCONS_INSTALL'] + '/' + package + '/' + project
build = envdismphfile['PRJ_SCONS_BUILD'] + '/' + package + '/' + project
libList = ['dismphfile','LineAccessor']
envdismphfile.PrependUnique(LIBS = libList)
module = envdismphfile.LoadableModule(target = 'dismphfile.abi3.so', source = 'dismphfilemodule.cpp') 
envdismphfile.Install(install,module)
envdismphfile.Alias('install',install)
envdismphfile.Install(build,module)
envdismphfile.Alias('build',build)
