#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# copyright: 2010 to the present, california institute of technology.
# all rights reserved. united states government sponsorship acknowledged.
# any commercial use must be negotiated with the office of technology transfer
# at the california institute of technology.
# 
# this software may be subject to u.s. export control laws. by accepting this
# software, the user agrees to comply with all applicable u.s. export laws and
# regulations. user has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# installation and use of this software is restricted by a license agreement
# between the licensee and the california institute of technology. it is the
# user's responsibility to abide by the terms of the license agreement.
#
# Author: Giangi Sacco
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





import os

Import('envalosreformat')
envALOS_fbs2fbd = envalosreformat.Clone()
package = envALOS_fbs2fbd['PACKAGE']
project = 'ALOS_fbs2fbd'
envALOS_fbs2fbd['PROJECT'] = project
Export('envALOS_fbs2fbd')

bindingsScons = os.path.join('bindings','SConscript')
bindingsVarDir = os.path.join(envALOS_fbs2fbd['PRJ_SCONS_BUILD'],package,project,'bindings')
SConscript(bindingsScons,variant_dir = bindingsVarDir)

includeScons = os.path.join('include','SConscript')
SConscript(includeScons)

install = os.path.join(envALOS_fbs2fbd['PRJ_SCONS_INSTALL'],package,project)
initFile = '__init__.py'
listFiles = ['ALOS_fbs2fbdPy.py',initFile]
envALOS_fbs2fbd.Install(install,listFiles)
envALOS_fbs2fbd.Alias('install',install)

