#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# copyright: 2010 to the present, california institute of technology.
# all rights reserved. united states government sponsorship acknowledged.
# any commercial use must be negotiated with the office of technology transfer
# at the california institute of technology.
# 
# this software may be subject to u.s. export control laws. by accepting this
# software, the user agrees to comply with all applicable u.s. export laws and
# regulations. user has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# installation and use of this software is restricted by a license agreement
# between the licensee and the california institute of technology. it is the
# user's responsibility to abide by the terms of the license agreement.
#
# Author: Giangi Sacco
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





import os

Import('envresamp_image')
package = envresamp_image['PACKAGE']
project = envresamp_image['PROJECT']
install = envresamp_image['PRJ_SCONS_INSTALL'] + '/' + package + '/' + project
build = envresamp_image['PRJ_SCONS_BUILD'] + '/' + package + '/' + project
libList = ['resamp_image','resampLib','utilLib','DataAccessor','InterleavedAccessor','StdOEL']
envresamp_image.PrependUnique(LIBS = libList)
module = envresamp_image.LoadableModule(target = 'resamp_image.abi3.so', source = 'resamp_imagemodule.cpp') 
envresamp_image.Install(install,module)
envresamp_image.Alias('install',install)
envresamp_image.Install(build,module)
envresamp_image.Alias('build',build)
