#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# copyright: 2015 to the present, california institute of technology.
# all rights reserved. united states government sponsorship acknowledged.
# any commercial use must be negotiated with the office of technology transfer
# at the california institute of technology.
# 
# this software may be subject to u.s. export control laws. by accepting this
# software, the user agrees to comply with all applicable u.s. export laws and
# regulations. user has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# installation and use of this software is restricted by a license agreement
# between the licensee and the california institute of technology. it is the
# user's responsibility to abide by the terms of the license agreement.
#
# Author: Joshua Cohen
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




import os

Import('envcontrib')
envrfi = envcontrib.Clone()
package = envrfi['PACKAGE']
project = 'rfi'
envrfi['PROJECT'] = project
install = os.path.join(envrfi['PRJ_SCONS_INSTALL'],package,project)
Export('envrfi')
initFile = '__init__.py'
if not os.path.exists(initFile):
    fout = open(initFile,'w')
    fout.write('#!/usr/bin/env python3')
    fout.close()

listFiles = [initFile,'mask.py']
envrfi.Install(install,listFiles)
envrfi.Alias('install',install)
