#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# copyright: 2010 to the present, california institute of technology.
# all rights reserved. united states government sponsorship acknowledged.
# any commercial use must be negotiated with the office of technology transfer
# at the california institute of technology.
# 
# this software may be subject to u.s. export control laws. by accepting this
# software, the user agrees to comply with all applicable u.s. export laws and
# regulations. user has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# installation and use of this software is restricted by a license agreement
# between the licensee and the california institute of technology. it is the
# user's responsibility to abide by the terms of the license agreement.
#
# Author: Walter Szeliga
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



#!/usr/bin/env python

import os
import fnmatch

Import('envSensordb')
envSensordbERS = envSensordb.Clone()
package = 'ers'
envSensordbERS['PACKAGE'] = package

listFiles = []
for root,dirs,files in os.walk(os.getcwd()):
        for file in files:
                if (fnmatch.fnmatch(file,'*.xml')):
                        listFiles.append(os.path.join(root,file))

install = os.path.join(envSensordb['SENSORDB_SCONS_INSTALL'],package)
envSensordbERS.Install(install,listFiles)
envSensordbERS.Alias('install',install)
Export('envSensordbERS')
