#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# copyright: 2010 to the present, california institute of technology.
# all rights reserved. united states government sponsorship acknowledged.
# any commercial use must be negotiated with the office of technology transfer
# at the california institute of technology.
# 
# this software may be subject to u.s. export control laws. by accepting this
# software, the user agrees to comply with all applicable u.s. export laws and
# regulations. user has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# installation and use of this software is restricted by a license agreement
# between the licensee and the california institute of technology. it is the
# user's responsibility to abide by the terms of the license agreement.
#
# Author: Giangi Sacco
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





import os

Import('envicu')
install = envicu['PRJ_LIB_DIR'] 
listFiles = ['icu.F','icuState.F','icuSetState.F','abs_phase.F','bermuda.F','gen_neutrons.F','grass.F','intf_cc.F','intf_filt.F','lowpass.F','norm_cor.F','ph_sigma.F','ph_slope.F','psfilt_sub.F','residues.F','rt.F','std_cor.F','unw_rt.F']
lib = envicu.Library(target = 'icu', source = listFiles)
envicu.Install(install,lib)
envicu.Alias('install',install)
