#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# copyright: 2011 to the present, california institute of technology.
# all rights reserved. united states government sponsorship acknowledged.
# any commercial use must be negotiated with the office of technology transfer
# at the california institute of technology.
# 
# this software may be subject to u.s. export control laws. by accepting this
# software, the user agrees to comply with all applicable u.s. export laws and
# regulations. user has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# installation and use of this software is restricted by a license agreement
# between the licensee and the california institute of technology. it is the
# user's responsibility to abide by the terms of the license agreement.
#
# Author: Eric Gurrola
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





import os

Import('envcontrib')
envmdx = envcontrib.Clone()

OPTIMIZATION = ''
envmdx.Replace(FORTRANFLAGS = str(envmdx['FORTRANFLAGS']).replace(str(envmdx['COMPILER_OPTIMIZATION']),OPTIMIZATION).split())
envmdx.Replace(CCFLAGS = str(envmdx['CCFLAGS']).replace(str(envmdx['COMPILER_OPTIMIZATION']),OPTIMIZATION).split())

envmdx['PACKAGE'] = envcontrib['PACKAGE']
envmdx['INSTALL_COMPS'] = envcontrib['INSTALL_COMPS']
envmdx['INSTALL_APPS'] = envcontrib['INSTALL_APPS']
package = envmdx['PACKAGE']
project = 'mdx'
build = os.path.join(envmdx['PRJ_SCONS_BUILD'],package,project)
envmdx['PROJECT'] = project
Export('envmdx')

src = os.path.join('src','SConscript')
SConscript(src,variant_dir=os.path.join(build,'src'))
