#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# copyright: 2010 to the present, california institute of technology.
# all rights reserved. united states government sponsorship acknowledged.
# any commercial use must be negotiated with the office of technology transfer
# at the california institute of technology.
# 
# this software may be subject to u.s. export control laws. by accepting this
# software, the user agrees to comply with all applicable u.s. export laws and
# regulations. user has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# installation and use of this software is restricted by a license agreement
# between the licensee and the california institute of technology. it is the
# user's responsibility to abide by the terms of the license agreement.
#
# Author: Giangi Sacco
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





import os

Import('envsch2orbit')
package = envsch2orbit['PACKAGE']
install = envsch2orbit['PRJ_SCONS_INSTALL'] + '/' + package
build = envsch2orbit['PRJ_SCONS_BUILD'] + '/' + package
libList = ['sch2orbit', 'orbitLib', 'utilLib', 'StdOEL']
envsch2orbit.PrependUnique(LIBS = libList)
module = envsch2orbit.LoadableModule(target = 'sch2orbit.abi3.so', source = 'sch2orbitmodule.cpp') 
envsch2orbit.Install(install,module)
envsch2orbit.Alias('install',install)
envsch2orbit.Install(build,module)
envsch2orbit.Alias('build',build)
