#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# copyright: 2010 to the present, california institute of technology.
# all rights reserved. united states government sponsorship acknowledged.
# any commercial use must be negotiated with the office of technology transfer
# at the california institute of technology.
# 
# this software may be subject to u.s. export control laws. by accepting this
# software, the user agrees to comply with all applicable u.s. export laws and
# regulations. user has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# installation and use of this software is restricted by a license agreement
# between the licensee and the california institute of technology. it is the
# user's responsibility to abide by the terms of the license agreement.
#
# Author: Giangi Sacco
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



#!/usr/bin/env python

import os

Import('envisceobj')
envImageFilter = envisceobj.Clone()
project = 'ImageFilter'
envImageFilter['PROJECT'] = project
package = envImageFilter['PACKAGE']
Export('envImageFilter')
install = os.path.join(envImageFilter['PRJ_SCONS_INSTALL'], package, project)

listFiles = ['__init__.py', 'ImageFilter.py', 'FilterFactory.py',
    'BandExtractor.py', 'ComplexExtractor.py']

envImageFilter.Install(install,listFiles)
envImageFilter.Alias('install',install)

includeScons = os.path.join('include', 'SConscript')
SConscript(includeScons)

bindingsScons = os.path.join('bindings', 'SConscript')
SConscript(bindingsScons, variant_dir = os.path.join(
    envImageFilter['PRJ_SCONS_BUILD'], package, project, 'bindings'))

srcScons = os.path.join('src', 'SConscript')
SConscript(srcScons, variant_dir = os.path.join(
    envImageFilter['PRJ_SCONS_BUILD'], package, project, 'src'))
