#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# copyright: 2012 to the present, california institute of technology.
# all rights reserved. united states government sponsorship acknowledged.
# any commercial use must be negotiated with the office of technology transfer
# at the california institute of technology.
# 
# this software may be subject to u.s. export control laws. by accepting this
# software, the user agrees to comply with all applicable u.s. export laws and
# regulations. user has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# installation and use of this software is restricted by a license agreement
# between the licensee and the california institute of technology. it is the
# user's responsibility to abide by the terms of the license agreement.
#
# Author: Giangi Sacco
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





import os

Import('envEstimateOffsets')
package = envEstimateOffsets['PACKAGE']
project = envEstimateOffsets['PROJECT']
install = envEstimateOffsets['PRJ_SCONS_INSTALL'] + '/' + package 
build = envEstimateOffsets['PRJ_SCONS_BUILD'] + '/' + package 
libList = ['estimateoffsets','DataAccessor','InterleavedAccessor','utilLib','fftw3f']
envEstimateOffsets.PrependUnique(LIBS = libList)
module = envEstimateOffsets.LoadableModule(target = 'estimateoffsets.abi3.so', source = 'estimateoffsetsmodule.cpp') 
envEstimateOffsets.Install(install,module)
envEstimateOffsets.Alias('install',install)
envEstimateOffsets.Install(build,module)
envEstimateOffsets.Alias('build',build)
